catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('spisokmenus/', views.SpisokMenuListView.as_view(), name='spisokmenus'),
    path('spisokmenu/<int:pk>', views.SpisokMenuDetailView.as_view(), name='spisokmenu-detail'),
    path('sponsors/', views.SponsorListView.as_view(), name='sponsors'),
    path('sponsor/<int:pk>', views.SponsorDetailView.as_view(), name='sponsor-detail'),
]

farizasushi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
# Use include() to add paths from the catalog application 
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

# Create your models here.
class Sushitype(models.Model):
    """
    Model representing  sushitype (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Dobavite type sushi (e.g. Science Fiction, French Poetry etc.)")
    
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class SpisokMenu(models.Model):
    """
    Model representing a  SpisokMenu (but not a specific copy of a SpisokMenu).
    """
    sushiname = models.CharField(max_length=200)
    sponsor = models.ForeignKey('Sponsor', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple
    # Author as a string rather than object because it hasn't been declared yet in the file.
    resept = models.TextField(max_length=1000, help_text='SushiResept')
    sushiprice = models.CharField('SushiPrice',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">SushiPrice number</a>')
    sushitype = models.ManyToManyField(Sushitype, help_text='Sushitype')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.sushiname
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this spisokmenu.
        """
        return reverse('spisokmenu-detail', args=[str(self.id)])

class Sponsor(models.Model):
    """
    Model representing an author.
    """
    sponsor_name = models.CharField(max_length=100)
    sponsor_kala = models.CharField(max_length=100)
    zakaz_product = models.DateField(null=True, blank=True)
    printitya_zakaz = models.DateField('printitya_zakaz', null=True, blank=True)

    class Meta:
        ordering = ["sponsor_kala","sponsor_name"]
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('sponsor-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}, {1}'.format(self.sponsor_kala,self.sponsor_name)

catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import SpisokMenu, Sponsor, Sushitype

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_spisokmenus=SpisokMenu.objects.all().count()
  
    num_sponsors=Sponsor.objects.count()  # The 'all()' is implied by default.

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_spisokmenus':num_spisokmenus,'num_sponsors':num_sponsors},
    )
from django.views import generic

class SpisokMenuListView(generic.ListView):
    model = SpisokMenu


class SpisokMenuDetailView(generic.DetailView):
    model = SpisokMenu

class SponsorListView(generic.ListView):
    model = Sponsor


class SponsorDetailView(generic.DetailView):
    model = Sponsor

catalog/templates/akci.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="color:DarkRed; background-color:#FFFACD">
  <div lass="col-xs-12 col-sm-12 col-md-8 col-lg-9">
		<div class="row">
		<div id="phone" class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-md-push-8 col-lg-push-9">

			<div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px"> 📱Байланыс📱</b></span><div></div></ul>
                <span><i class="fa fa-phone"></i>8 (727) 354 58 40 </span>
									<span><i class="fa fa-mobile"></i>8(747)-586-08 22</span>
									<span><i class="fa fa-whatsapp"></i>8(747)-586-08 22</span>
									<span><i class="fa fa-whatsapp"></i>8(775)-232 64 83</span>
																	</div>
            <div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">🔥 Жеңілдіктер📢 </b></span><div></div></ul>
                <span><p class="fa fa-phone"></p>3000 теңге + "Сяке маки"  </span>
									<span> <p class="fa fa-whatsapp"> 5000 теңге + "Спайс ролл</p></span>
									<span><p class="fa fa-whatsapp"></p>7000 теңге + "Филадельфия маки"</span>
									<span><p class="fa fa-whatsapp"></p>2 Сяке-маки +1л кола</span>
                <span><a  href="https://youtu.be/FbHzYxi2YaA" style="color:#FF0000">>>>акция видио<<<</a></span>

																	</div>
            <div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">📜 Жаңалықтар</b></span><div></div></ul>
                <span><p class="fa fa-phone"></p>📌"У Казахстана нет конфликтов": Назарбаев рассказал о разговоре с Трампом </span>
									<span><p class="fa fa-mobile"></p>📌Головкин назвал виновного в «эффекте GGG», вселяющем страх в соперников</span>
									<span><p class="fa fa-whatsapp"></p>📌В Караганде отметили День единства народа Казахстана</span>
									<span><p class="fa fa-whatsapp"></p>📌Первая солнечная электростанция запущена в Мангистау</span>
                <span><a href="https://www.nur.kz/	" style="color:red" class="fa fa-whatsapp">📌Тағы>>></a></span>
            </div>

		</div>

		<div id="links" class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-md-pull-4 col-lg-pull-3">
			<div class="hidden-md">
			<ul><a style=" font-size:18px;color:#8B0000" href="https://2gis.kz/almaty" title="🚗 Карта доставки 🚗">🚗Жеткізу картасы🚗</a>
												</ul>

		</div>

<div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}

               <table width="780" height="49" border="0" cellpadding="0" cellspacing="0" class="sidebar-nav">
    <tr>
      <ul class="sidebar-nav">

          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'index' %}">Үй    </a></strong></li>
          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'spisokmenus' %}"> Суши Меню</a></strong></li>
          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'sponsors' %}">Демеушілер</a> </strong></li>
     	  <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="">SushiTypes</a></strong></li>


      </ul>
    </tr>
  </table>


     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/akcia.html
{% extends "base_generic.html" %}

{% block content %}
<div style="width: 785px;background: #ccc;padding: 5px;padding-right: 5px; border: outset 5px BurlyWood;
" >
   <div class="SpisokMenu" style="color:MidnightBlue; background-color:#ccc; width:300px">

</div>
    <h1 align="center">SushiMenu List</h1>

    {% if spisokmenu_list %}
    <ul>

      {% for spisokmenu in spisokmenu_list %}
      <li>
        <a style="font-size:20px; color:#000000" href="{{ spisokmenu.get_absolute_url }}">{{ spisokmenu.sushiname }}🍣 </a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      
    {% endif %}       
{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
  <nav class='green'>
    <div class="nav-wrapper">
      <ul class="right hide-on-med-and-down">
        {% if user.username %}
        <li>Hello,{{user.username}} </li>
        {% endif %}


      </ul>
    </div>
  </nav>
<body style="color:DarkRed; background-color:#FFFACD">
  <div lass="col-xs-12 col-sm-12 col-md-8 col-lg-9">
		<div class="row">
		<div id="phone" class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-md-push-8 col-lg-push-9">

			<div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">Байланыс📱</b></span><div></div></ul>
                <span><i class="fa fa-phone"></i>8 (727) 354 58 40 </span>
									<span><i class="fa fa-mobile"></i>8(747)-586-08 22</span>
									<span><i class="fa fa-whatsapp"></i>8(747)-586-08 22</span>
									<span><i class="fa fa-whatsapp"></i>8(775)-232 64 83</span>
																	</div>
            <div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">🔥 Жеңілдіктер📢 </b></span><div></div></ul>
                <span><p class="fa fa-phone"></p>3000 теңге + "Сяке маки"  </span>
									<span> <p class="fa fa-whatsapp"> 5000 теңге + "Спайс ролл</p></span>
									<span><p class="fa fa-whatsapp"></p>7000 теңге + "Филадельфия маки"</span>
									<span><p class="fa fa-whatsapp"></p>2 Сяке-маки +1л кола</span>
                <span><a  href="https://youtu.be/FbHzYxi2YaA" style="color:#FF0000">>>>акция видио<<<</a></span>

																	</div>
            <div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">📜 Жаңалықтар</b></span><div></div></ul>
                <span><p class="fa fa-phone"></p>📌"«Қазақстандағы қақтығыстар жоқ»: Назарбаев Трамппен әңгімелесу туралы әңгімелеп берді</span>
                                <span><p class="fa fa-mobile"></p>📌Головкин «GGG әсерін» бәсекелестердің қорқынышын тудырады</span>
									<span><p class="fa fa-whatsapp"></p>📌Қарағандыда Қазақстан халқының бірлігі күні атап өтілді</span>
									<span><p class="fa fa-whatsapp"></p>📌Маңғыстауда алғашқы күн электр станциясы іске қосылды</span>
                <span><a href="https://www.nur.kz/	" style="color:red" class="fa fa-whatsapp">📌Тағы>>></a></span>
            </div>

		</div>

		<div id="links" class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-md-pull-4 col-lg-pull-3">
			<div class="hidden-md">
			<ul><a style=" font-size:18px;color:#8B0000" href="https://2gis.kz/almaty" title="🚗 Карта доставки 🚗">🚗Жеткізу картасы🚗</a>
												</ul>

		</div>

<div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}

               <table width="780" height="49" border="0" cellpadding="0" cellspacing="0" class="sidebar-nav">
    <tr>
      <ul class="sidebar-nav">

          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'index' %}">Үй    </a></strong></li>
          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'spisokmenus' %}"> Суши Меню</a></strong></li>
          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'sponsors' %}">Демеушілер</a> </strong></li>
     	  <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="akcia.html">Суреттер</a></strong></li>


      </ul>
    </tr>
  </table>


     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>

      </div>
          <div class="top-bl">
              <div class="container">
                  <div class="card">
                      <b style="color:white;">rjhflf</b>
                  </div>
              </div>
          </div>
  {% endif %}
{% endblock %}

</body>
</html>

catalog/templates/catalog/akci.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="color:DarkRed; background-color:#FFFACD">
  <div lass="col-xs-12 col-sm-12 col-md-8 col-lg-9">
		<div class="row">
		<div id="phone" class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-md-push-8 col-lg-push-9">

			<div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px"> 📱Байланыс📱</b></span><div></div></ul>
                <span><i class="fa fa-phone"></i>8 (727) 354 58 40 </span>
									<span><i class="fa fa-mobile"></i>8(747)-586-08 22</span>
									<span><i class="fa fa-whatsapp"></i>8(747)-586-08 22</span>
									<span><i class="fa fa-whatsapp"></i>8(775)-232 64 83</span>
																	</div>
            <div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">🔥 Жеңілдіктер📢 </b></span><div></div></ul>
                <span><p class="fa fa-phone"></p>3000 теңге + "Сяке маки"  </span>
									<span> <p class="fa fa-whatsapp"> 5000 теңге + "Спайс ролл</p></span>
									<span><p class="fa fa-whatsapp"></p>7000 теңге + "Филадельфия маки"</span>
									<span><p class="fa fa-whatsapp"></p>2 Сяке-маки +1л кола</span>
                <span><a  href="https://youtu.be/FbHzYxi2YaA" style="color:#FF0000">>>>акция видио<<<</a></span>

																	</div>
            <div class="dropdown" style="width: 200px;background: #ccc;padding: 5px;padding-right: 20px; border: outset 5px BurlyWood;
    float: left;" >
				<ul>                   <a  class="fa fa-share"></a><b style="font-size:18px">📜 Жаңалықтар</b></span><div></div></ul>
                <span><p class="fa fa-phone"></p>📌"У Казахстана нет конфликтов": Назарбаев рассказал о разговоре с Трампом </span>
									<span><p class="fa fa-mobile"></p>📌Головкин назвал виновного в «эффекте GGG», вселяющем страх в соперников</span>
									<span><p class="fa fa-whatsapp"></p>📌В Караганде отметили День единства народа Казахстана</span>
									<span><p class="fa fa-whatsapp"></p>📌Первая солнечная электростанция запущена в Мангистау</span>
                <span><a href="https://www.nur.kz/	" style="color:red" class="fa fa-whatsapp">📌Тағы>>></a></span>
            </div>

		</div>

		<div id="links" class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-md-pull-4 col-lg-pull-3">
			<div class="hidden-md">
			<ul><a style=" font-size:18px;color:#8B0000" href="https://2gis.kz/almaty" title="🚗 Карта доставки 🚗">🚗Жеткізу картасы🚗</a>
												</ul>

		</div>

<div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}

               <table width="780" height="49" border="0" cellpadding="0" cellspacing="0" class="sidebar-nav">
    <tr>
      <ul class="sidebar-nav">

          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'index' %}">Үй    </a></strong></li>
          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'spisokmenus' %}"> Суши Меню</a></strong></li>
          <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="{% url 'sponsors' %}">Демеушілер</a> </strong></li>
     	  <li><strong> <a style="background:#8B0000; font-size:18px;color:#FFFACD" href="">SushiTypes</a></strong></li>


      </ul>
    </tr>
  </table>


     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/cafe.html
<!DOCTYPE >
<html >
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>FariDin</title>
    <link href="css/cafee.css" rel="stylesheet" type="text/css" />
</head>
<body>
<!-- begin #container -->
<div id="container">
    <!-- begin #header -->
    <div id="header">
        <div class="headerTop">
            <div class="menu">
                <ul>
                    <li id="index.html"><a href="">Басты бет</a></li>
                    <li><a href="cafe.html"> Кафе туралы</a></li>
                    <li><a href="menu.html">Суреттер</a></li>
                    <li><a href="https://vk.com/im">Байланысу</a></li>
                    <li><a href="">Мекен-жайымыз</a></li>
                    </li>
                </ul>
            </div>
            <div class="icons">
                <ul class="icons">
                    <li><a href="https://twitter.com/?lang=ru"><img src="images/twitter.png" alt="" /></a></li>
                    <li><a href="https://del.icio.us/"><img src="images/delicious.png" alt="" /></a></li>
                    <li><a href="https://www.facebook.com/"><img src="images/facebook.png" alt="" /></a></li>
                    <li><a href="https://thefeed.com/"><img src="images/feed.png" alt="" /></a></li>
                    <li><a href=""><img src="images/flickr.png" alt="" /></a></li>
                    <li><a href=""><img src="images/linkedin.png" alt="" /></a></li>
                    <li><a href=""><img src="images/myspace.png" alt="" /></a></li>
                    <li><a href=""><img src="images/stumble.png" alt="" /></a></li>
                </ul>
            </div>
            <div class="clearfloat"></div>

    <!-- end #header -->
    <!-- begin #sidebar1 -->
    <div id="sidebar1">
        <div class="picBox">
            <div class="picBoxImage"><img src="images/111.jpg" width="200" height="300" alt="" /></div>


            <div class="clearfloat"></div>
        </div>
        <div class="picBox">
            <div class="clearfloat"></div>
        </div>
    </div>
    <!-- end #sidebar1 -->
    <!-- begin #mainContent -->
    <div id="mainContent">
        <h1>ФариДин суши кафесі туралы</h1>
        <br>
        <br /><br />
          ФариДин кафесі 2017 жылдың 1-ші қыркүйек айында негізін қалаған. 2016 жылы жоспарлап, оны қазіргідей дәрежеге жеткізген кафенің директорлары Халамханқызы Фариза және Карабалаева Динара.<br />
        <br /> ФариДин кафесі сіздерге тек қана сапалылық бермейді, сонымен қоса сіздерге зор сенімділік пен өмірге деген сәттілік алып келеді!<br />
        <br /> Біз өзгеруден қорықпаймыз. Әрқашан жаңарып, тәжірибе алмасып, таң қалдырудан жалықпаймыз! Және де біз әлемдік деңгейдегі адамдардың қауіпсіздігін қамтамасыз ететін бірегей кафе ретінде танымалмыз.<br /><br />
        <br></br>Қазірдің өзінде әлемдік деңгейдегі 10 мемлекеттің әйгілі суши ресторандарымен тәжірибе алмасып, біліктілікті жаңарту үстіндеміз.<br></br>
        </p>


    </div>
    <!-- end #mainContent -->
    <!-- This clearing element should immediately follow the #mainContent div in order to force the #container div to contain all child floats --><br class="clearfloat" />
    <!-- begin #footer -->
    <div id="footer">
        <p>
            Terms of Use | <a title="This page validates as XHTML 1.0 Strict" href="http://validator.w3.org/check/referer" class="footerLink"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> |
            <a title="This page validates as CSS" href="http://jigsaw.w3.org/css-validator/check/referer" class="footerLink"><abbr title="Cascading Style Sheets">CSS</abbr></a>  |  Copyright &copy; Private Pilates Club. Design by <a href="http://www.fbpager.com">Free Facebook Templates</a>.
        </p>
    </div>
    <!-- end #footer -->
</div>
<!-- end #container -->
</body>
</html>